spring:
  application:
    name: usb-data-publisher
app:
  connectionType: ANTENNA
    
socket.buffer.size: 1024
socket.poll.delay.ms: 100
serial.port.baud.rate: 38400
serial.port.data.bits.size: 8
serial.port.num.of.stop.bits: 1
serial.port.set.parity: 0